name = FIXME
main = "src/server/index.tsx"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat_v2"]

assets = {directory = 'public'}


[build]
command = "npm run build:css && npm run build:js"


# [[analytics_engine_datasets]]
# binding = "analytics"
# dataset = CHANGE_ME
